[fx][host-tool] Use GN label to avoid `fx build` warnings.
Use the tool's GN label when calling `fx build` to avoid annoying warnings.

+ Add directives to satisfy `shellcheck -x`.

Bug: 42084668
Change-Id: I4eeacc6a9550b575ab0949d22eead29faa0972f4
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1047154
Fuchsia-Auto-Submit: David Turner <digit@google.com>
Commit-Queue: Auto-Submit <auto-submit@fuchsia-infra.iam.gserviceaccount.com>
Reviewed-by: Oliver Newman <olivernewman@google.com>

diff --git a/tools/devshell/host-tool b/tools/devshell/host-tool
--- a/tools/devshell/host-tool
+++ b/tools/devshell/host-tool
@@ -27,7 +27,9 @@
 
 set -e
 
+# shellcheck source=tools/devshell/lib/vars.sh
 source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/vars.sh || exit $?
+# shellcheck source=tools/devshell/lib/host_symbolizer.sh
 source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/host_symbolizer.sh || exit $?
 fx-config-read
 
@@ -90,6 +92,7 @@ shift
 
 # list-build-artifacts fails with a reasonable error message if tool is unknown
 toolpath="$(fx-command-run list-build-artifacts --name "${toolname}" --expect-one tools)"
+tool_label="$(fx-command-run list-build-artifacts --show-label --name "${toolname}" --expect-one tools)"
 
 if [[ ! -f "${FUCHSIA_BUILD_DIR}/${toolpath}" ]]; then
   # If the desire is to build, then it's important for the build to
@@ -107,13 +110,13 @@ if [[ ! -f "${FUCHSIA_BUILD_DIR}/${toolpath}" ]]; then
 
   if ! $build; then
     fx-error "Tool \"${toolname}\" is required by this command and has not been built."
-    fx-error "Please build it first: fx build ${toolpath}"
+    fx-error "Please build it first: fx build ${tool_label}"
     exit 2
   fi
 
   {
-    echo "Building required tool \"${toolpath}\"..."
-    fx-command-run build "${toolpath}" || exit $?
+    echo "Building required tool '${toolname}' from \"${tool_label}\"..."
+    fx-command-run build "${tool_label}" || exit $?
   } 1>&2
 fi
 
