[devshell][serve] Detect rogue package-tool processes
In certain edge cases, e.g. sending SIGKILL to the `fx serve` process,
the started incremental package publisher is not terminated and may
continue to run. Upon starting, try to detect invalid cases and suggest
the probably appropriate action to the user.

Fixed: b/336282647
Change-Id: I2eebf8a8cc5b33752e2bdb84614f4c8e212a470b
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1036774
Fuchsia-Auto-Submit: Thomas Zander <thomasalpinus@google.com>
Reviewed-by: John Wittrock <wittrock@google.com>
Commit-Queue: Auto-Submit <auto-submit@fuchsia-infra.iam.gserviceaccount.com>

diff --git a/tools/devshell/serve b/tools/devshell/serve
--- a/tools/devshell/serve
+++ b/tools/devshell/serve
@@ -286,6 +286,14 @@ if is_feature_enabled "incremental" || is_feature_enabled "incremental_new"; the
   )
   package_tool_args=( repository publish "${repo_dir}" "${package_tool_flags[@]}" )
 
+  # Check for erroneously running instances of package-tool
+  package_tool_pids=$(pgrep -f "package-tool repository publish $(fx get-build-dir)/amber-files --watch")
+  if [[ -n $package_tool_pids ]]; then
+    fx-error "Incremental auto-publisher for this build config is/are already running under pid(s): $(echo $package_tool_pids)."
+    fx-error "This is probably an error. Please terminate the auto-publisher process(es) and restart."
+    exit 1
+  fi
+
   # the manifest list file has relative paths and package manifest watcher looks for them
   # from PWD, so the command needs to be executed in "$FUCHSIA_BUILD_DIR"
   if [[ "${verbose}" == true ]]; then
