[devshell][add-test] Revert args.gn on fx-gen failure
Cache and restore args.gn if fx-gen fails so that the user doesn't have
to edit their args.gn to get their build back into a working state.

Change-Id: Ic80dc9b2bf16fc8ec551f682c90fa723241be110
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1031994
Reviewed-by: Yifei Teng <yifeit@google.com>
Commit-Queue: Auto-Submit <auto-submit@fuchsia-infra.iam.gserviceaccount.com>
Fuchsia-Auto-Submit: Christopher Anderson <cja@google.com>

diff --git a/tools/devshell/contrib/add-test b/tools/devshell/contrib/add-test
--- a/tools/devshell/contrib/add-test
+++ b/tools/devshell/contrib/add-test
@@ -20,7 +20,11 @@ fx-config-read
 
 set -e
 
+# Cache args in case of typos, bad paths, etc.
 args_gn="${FUCHSIA_BUILD_DIR}/args.gn"
+backup_args_gn="$(mktemp --suffix=.args.gn)"
+cp "${args_gn}" "${backup_args_gn}"
+
 echo "Adding test labels to ${args_gn}"
 
 for arg in "$@"; do
@@ -33,5 +37,10 @@ for arg in "$@"; do
 done
 
 echo "Generating Ninja outputs file"
+if ! fx-gen; then
+    echo "fx gen failed, restoring original args.gn and re-running 'fx gen'"
+    cp "${backup_args_gn}" "${args_gn}"
+    fx-gen
+fi
 
-fx-gen
+rm -f "${backup_args_gn}"
