[mkinstaller] Do not use --mkpath argument in rsync.
macOS (as of 14.4) uses rsync 2.6.9 by default, which doesn't
support the --mkpath argument.

This change replaces the --mkpath argument with a "mkdir -p"
command which are well supported by most OSes.

Test: fx mkinstaller-remote <HOSTNAME> /ssd/fuchsia /dev/disk4
      where the /dev/disk4 is the USB flash drive.
Change-Id: I783c8fdacd0d839b17bfcb3314f139e18b6e6c81
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1010895
Reviewed-by: David Pursell <dpursell@google.com>
Commit-Queue: Yilong Li <liyl@google.com>

diff --git a/tools/devshell/contrib/mkinstaller-remote b/tools/devshell/contrib/mkinstaller-remote
--- a/tools/devshell/contrib/mkinstaller-remote
+++ b/tools/devshell/contrib/mkinstaller-remote
@@ -63,10 +63,16 @@ if ! remote_path=$(ssh "${host}" \
   exit 1
 fi
 
-LOCAL_PATH="${FUCHSIA_DIR}/out/fetched/installer.img"
+local_image_dir="${FUCHSIA_DIR}/out/fetched"
+if ! mkdir -p ${local_image_dir}; then
+  fx-error "failed to create directory for the fetched installer image"
+  exit 1
+fi
+
+local_path="${local_image_dir}/installer.img"
 
 fx-info "Copying installer image to local host"
-rsync --compress --partial --progress --mkpath "${host}:${remote_path}" "${LOCAL_PATH}"
+rsync --compress --partial --progress "${host}:${remote_path}" "${local_path}"
 
 # Clean up the remote temp dir.
 remote_dir=$(dirname "${remote_path}")
@@ -75,4 +81,4 @@ ssh "${host}" rm -rf \"${remote_dir}\"
 # Now write the image to the final requested location.
 # We could just `dd` here, but mkinstaller has some safety-checks for the
 # output path that we want to retain.
-fx-command-run mkinstaller "$@" --from-image "${LOCAL_PATH}"
+fx-command-run mkinstaller "$@" --from-image "${local_path}"
